name: Update TinyTeX Formula

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:
  push:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify wget is installed
        run: |
          wget --version

      - name: Get latest TinyTeX version
        run: |
          url="https://github.com/rstudio/tinytex-releases/releases/latest"
          redirect_url=$(curl -s -o /dev/null -w '%{redirect_url}' "$url")
          echo "Redirect URL: $redirect_url"

          version="${redirect_url##*/tag/}"
          echo "Version: $version"

          echo "tinytex_version=$version" >> $GITHUB_ENV

      - name: Print TinyTeX version
        run:
          echo "tinyex_version ${{ env.tinytex_version }}"

      - name: Update TinyTeX Formula
        run: |
          wget https://github.com/rstudio/tinytex-releases/releases/download/$tinytex_version/TinyTeX-1-$tinytex_version.tar.gz

          sha256=$(shasum -a 256 TinyTeX-1-$tinytex_version.tar.gz | awk '{print $1}')

          sed -i.bak "s/sha256 \"[a-f0-9]*\"/sha256 \"$sha256\"/" Formula/tinytex.rb
          sed -i.bak "s/v[0-9]*\.[0-9]*\.[0-9]*/$tinytex_version/" Formula/tinytex.rb

          rm Formula/tinytex.rb.bak

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update TinyTeX to $tinytex_version"
          git push
        continue-on-error: true