name: Update TinyTeX Formula

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:
  push:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          brew update
          brew upgrade

          brew install wget

      - name: Update TinyTeX Formula
        run: |
          version=$(curl -s https://github.com/rstudio/tinytex-releases/releases/latest | grep -oP 'tag/\K[^"]+')

          wget https://github.com/rstudio/tinytex-releases/releases/download/$version/TinyTeX-1-$version.tar.gz

          sha256=$(shasum -a 256 TinyTeX-1-$version.tar.gz | awk '{print $1}')

          sed -i.bak "s/sha256 \"[a-f0-9]*\"/sha256 \"$sha256\"/" Formula/tinytex.rb
          sed -i.bak "s/v[0-9]*\.[0-9]*\.[0-9]*/v$version/" Formula/tinytex.rb

          rm Formula/tinytex.rb.bak

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update TinyTeX to $version"
          git push