name: Update TinyTeX Formula

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Update TinyTeX Formula
        run: |
          brew update
          brew upgrade
          brew install wget
          wget https://github.com/yihui/tinytex-releases/releases/latest/download/TinyTeX-1-latest.tar.gz
          sha256=$(shasum -a 256 TinyTeX-1-latest.tar.gz | awk '{print $1}')
          sed -i.bak "s/sha256 \"[a-f0-9]*\"/sha256 \"$sha256\"/" Formula/tinytex.rb
          sed -i.bak "s/v[0-9]*\.[0-9]*\.[0-9]*/v$(date +%Y.%m.%d)/" Formula/tinytex.rb
          rm Formula/tinytex.rb.bak
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Update TinyTeX to latest release"
          git push